apiVersion: v1
kind: Secret

metadata:
  name: app-secret
  namespace: microservices

type: Opaque

stringData:
  JWT_SECRET: "d3c53c608056cad171daae923b0a3e3685014d84cf33c57a1c52128cb387d4da7edbdc887278ada73aa27b7a6f2b25927da6f66decf361bd8c9fca5cd1579d40"

  DATABASE_URL: postgresql://postgres:jnba2236%24%24@postgres:5432/user_db

  PRODUCT_DATABASE_URL: "postgresql://postgres:jnba2236$$@postgres:5432/product_db"

  ORDER_DATABASE_URL: "postgresql://postgres:jnba2236$$@postgres:5432/order_db"

  PAYMENT_DATABASE_URL: "postgresql://postgres:jnba2236$$@postgres:5432/payment_db"

  NOTIFICATION_DATABASE_URL: "postgresql://postgres:jnba2236$$@postgres:5432/notification_db"

