apiVersion: v1
kind: Secret

metadata:
  name: order-secret
  namespace: microservices

type: Opaque

stringData:
  JWT_SECRET: "d3c53c608056cad171daae923b0a3e3685014d84cf33c57a1c52128cb387d4da7edbdc887278ada73aa27b7a6f2b25927da6f66decf361bd8c9fca5cd1579d40"

  DATABASE_URL: "postgresql://postgres:jnba2236%24%24@host.docker.internal:5432/order_db?schema=public"