apiVersion: batch/v1
kind: Job
metadata:
  name: product-db-init
  namespace: microservices
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: prisma-migrate
          image: 792705600668.dkr.ecr.ap-south-1.amazonaws.com/product-service:latest
          imagePullPolicy: Always

          envFrom:
            - secretRef:
                name: product-secret
          command:
            - npx
            - prisma
            - migrate
            - deploy
            - --schema=src/prisma/schema.prisma