apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service
  namespace: microservices
  labels:
    app: product-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: product-service

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
        - name: product-service
          image: product-service:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 4002
          
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: product-secret
          

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 4002
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 4002  
            initialDelaySeconds: 20
            periodSeconds: 10