apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway
  namespace: microservices
  labels:
    app: api-gateway

spec:
  replicas: 2

  selector:
    matchLabels:
      app: api-gateway

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway
          image: 792705600668.dkr.ecr.ap-south-1.amazonaws.com/api-gateway:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 4000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 5

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: user-secret